[project]
name = "image-processing"
version = "0.1.0"
description = "Image processing for particle displacement analysis"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "opencv-python>=4.1.1",
    "numpy>=1.23.5",
    "matplotlib>=3.3",
]
